#Info: This file contains the messages that will be displayed on the screen

INFO_MESSAGES = {'PT': {'START': 'Iniciando comunicação com o dispositivo...',
                        'INFO': 'Informação do dispositivo recebidas com sucesso!',    
                        'ERROR': 'Erro ao coletar dados! Verifique o dispositivo, reinicie e tente novamente!',
                        'COLLECTING': 'Iniciando a Recolha de dados, por favor aguarde!',
                        'HOLD': 'Por favor aguarde!',
                        'STX_ERROR': 'STX não encontrado!',
                        'SUCCESS': 'Dados recolhidos com sucesso!',
                        'TEST': 'Teste de leitura do Dispositivo!',
                        'COLLEDTED': 'Dados recolhidos:',
                        'CSV': 'Exportado para CSV...',
                        'INVALID_TYPE': 'Tipo de exportação inválido!',
                        'READ': 'Modo de Leitura!',
                        'CONFIG': 'Modo de Configuração!',
                        'TESTMOD': 'Modo de Teste!',
                        'LER': 'Ler Contador',
                        'SAIR': 'Sair',
                        'IMAGE': 'Imagem do Dispositivo',
                        'MARCA': 'Marca',
                        'MODELO': 'Modelo',
                        'ID': 'ID',
                        'BRAND': 'Marca',
                        'MODEL': 'Modelo',
                        'ID': 'ID',
                        'NO_PORTS': 'Porta não encontrada!',
                        'FOUND': 'Porta(s) encontrada(s)',
                        'WILL_BE_USED': 'será usada a porta',
                        'CHECK': 'Verifique a existência de uma porta série e tente novamente!',
                        'INTRO': 'Leitor de contadores de energia',
                        'VERSION': '1.0.0',
                        'AUTHOR': 'GLOBALEDA - pmleite',
                        'LICENSE': 'Propriedade da GlobalEDA'},

                # English
                'EN':  {'START': 'Starting communication with the device...',
                        'INFO': 'Device information received successfully!',
                        'ERROR': 'Error collecting data! Check the device, restart and try again!',
                        'COLLECTING': 'Starting collecting data, please wait!',
                        'HOLD': 'Please wait!',
                        'STX_ERROR': 'STX not found!',
                        'SUCCESS': 'Data collected successfully!',
                        'TEST': 'Device reading test!',
                        'COLLEDTED': 'Data collected:',
                        'CSV': 'Exported to CSV...',
                        'INVALID_TYPE': 'Invalid export type!',
                        'READ': 'Read Mode!',
                        'CONFIG': 'Configuration Mode!',
                        'TESTMOD': 'Test Mode!',
                        'LER': 'Read Counter',
                        'SAIR': 'Exit',
                        'IMAGE': 'Device Image',
                        'MARCA': 'Brand',
                        'MODELO': 'Model',
                        'ID': 'ID',
                        'BRAND': 'Brand',
                        'MODEL': 'Model',
                        'ID': 'ID',
                        'NO_PORTS': 'Port not found!',
                        'FOUND': 'Port(s) found',
                        'WILL_BE_USED': 'will be used the port',
                        'CHECK': 'Check the existence of a serial port and try again!',
                        'INTRO': 'Energy meter reader',
                        'VERSION': '1.0.0',
                        'AUTHOR': 'GLOBALEDA - pmleite',
                        'LICENSE': 'GlobalEDA property'},

                # French       
                'FR':  {'START': 'Démarrage de la communication avec le dispositif...',
                        'INFO': 'Informations du dispositif reçues avec succès!',
                        'ERROR': 'Erreur de collecte de données! Vérifiez le dispositif, redémarrez et réessayez!',
                        'COLLECTING': 'Démarrage de la collecte de données, veuillez patienter!',
                        'HOLD': 'Veuillez patienter!',
                        'STX_ERROR': 'STX introuvable!',
                        'SUCCESS': 'Données collectées avec succès!',
                        'TEST': 'Test de lecture du dispositif!',
                        'COLLEDTED': 'Données collectées:',
                        'CSV': 'Exporté vers CSV...',
                        'INVALID_TYPE': 'Type d\'exportation invalide!',
                        'READ': 'Mode de lecture!',
                        'CONFIG': 'Mode de configuration!',
                        'TESTMOD': 'Mode de test!',
                        'LER': 'Lire le compteur',
                        'SAIR': 'Sortie',
                        'IMAGE': 'Image du dispositif',
                        'MARCA': 'Marque',
                        'MODELO': 'Modèle',
                        'ID': 'ID',
                        'BRAND': 'Marque',
                        'MODEL': 'Modèle',
                        'ID': 'ID',
                        'NO_PORTS': 'Port non trouvé!',
                        'FOUND': 'Port(s) trouvé',
                        'WILL_BE_USED': 'sera utilisé le port',
                        'CHECK': 'Vérifiez l\'existence d\'un port série et réessayez!',
                        'INTRO': 'Lecteur de compteurs d\'énergie',
                        'VERSION': '1.0.0',
                        'AUTHOR': 'GLOBALEDA - pmleite',
                        'LICENSE': 'Propriété de GlobalEDA'}, 
                
                # Spanish 
                'ES':  {'START': 'Iniciando comunicación con el dispositivo...',
                        'INFO': 'Información del dispositivo recibida con éxito!',
                        'ERROR': 'Error al recopilar datos! Verifique el dispositivo, reinicie y vuelva a intentarlo!',
                        'COLLECTING': 'Iniciando la recopilación de datos, espere por favor!',
                        'HOLD': 'Por favor espere!',
                        'STX_ERROR': 'STX no encontrado!',
                        'SUCCESS': 'Datos recopilados con éxito!',
                        'TEST': 'Prueba de lectura del dispositivo!',
                        'COLLEDTED': 'Datos recopilados:',
                        'CSV': 'Exportado a CSV...',
                        'INVALID_TYPE': 'Tipo de exportación no válido!',
                        'READ': 'Modo de lectura!',
                        'CONFIG': 'Modo de configuración!',
                        'TESTMOD': 'Modo de prueba!',
                        'LER': 'Leer contador',
                        'SAIR': 'Salida',
                        'IMAGE': 'Imagen del dispositivo',
                        'MARCA': 'Marca',
                        'MODELO': 'Modelo',
                        'ID': 'ID',
                        'BRAND': 'Marca',
                        'MODEL': 'Modelo',
                        'ID': 'ID',
                        'NO_PORTS': 'Puerto no encontrado!',
                        'FOUND': 'Puerto(s) encontrado(s)',
                        'WILL_BE_USED': 'se usará el puerto',
                        'CHECK': 'Verifique la existencia de un puerto serie e intente nuevamente!',
                        'INTRO': 'Lector de contadores de energía',
                        'VERSION': '1.0.0',
                        'AUTHOR': 'GLOBALEDA - pmleite',
                        'LICENSE': 'Propiedad de GlobalEDA'},
                }